### ISSUE TITLE
Human readable time types

### ISSUE THREAD

**Issue by vandervecken** [palantir/conjure-java-runtime-api#152]
Can we provide human readable time types for weeks and months?
Useful for Foundry Retention.

**Comment by markelliot** [comment]
https://github.com/palantir/human-readable-types

**Comment by markelliot** [comment]
I think it's an oversight that it's not public, it's not deprecated.

**Comment by vinooganesh** [comment]
for clarity's sake, my statement was not that because the repo is private that would mean that this is deprecated. thought that was was strange that the repo was private, and given similar code here, was wondering if we were encouraging people to use conjure's version instead: https://github.com/palantir/conjure-java-runtime-api/blob/develop/service-config/src/main/java/com/palantir/conjure/java/api/config/service/HumanReadableDuration.java#L43

**Comment by vandervecken** [comment]
Ok, so can you make that repo public so I can add an issue to it (or figure out who can do this)?

**Comment by vandervecken** [comment]
Got access and filed https://github.com/palantir/human-readable-types/issues/1
